name: Build and Deploy To GH Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages:
    name: gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Install and Build
        run: |
          npm ci
          npm run build-site

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: site
